### ISSUE TITLE
캘린더 날짜 클릭시 get

### ISSUE THREAD

**Issue by rlorxl** [rlorxl/task-dashboard#1]
### Todo
- [x]  slice.date 변경
- [x] 클릭한 날짜 데이터요청
- [x] redux-thunk로 변경

**Comment by rlorxl** [comment]
### Problem

- 커스텀훅을 거치면 파이어베이스에서 데이터를 받아올 수 없음. 
<img width="769" alt="스크린샷 2022-11-05 오전 1 28 47" src="https://user-images.githubusercontent.com/90922593/200027001-e8d7495c-15d1-4d27-81b4-e8c8297474f4.png">

- 아예 useEffect에서 get요청을 바로 해야만 받아와짐. (왜...)

**Comment by rlorxl** [comment]
### Todo 

- get요청 redux-thunk로 변경

**Comment by rlorxl** [comment]
### Solve
- 커스텀 훅(useHttp)에 문제가 있어서 redux-thunk로 수정해서 해결함.
- 첫 마운트시에 getAll 요청을 하고 날짜 클릭시 바뀐 date에 따라 Task - taskData state가 변경되도록 수정.
